{% set name = "nccmp" %}
{% set version = "1.11.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/remikz/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: fbac27f69fa9582ecd43e54f24b8837670bcfcf9c15d0aa32c8d2356222a4d25

build:
  number: 0
  # Need to skip win because curl needs vc=9 and hdf5 needs vc>=14
  skip: true  # [win]

requirements:
  build:
    - make
    - cmake <4
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - curl
    - libcurl
    - hdf5
    - libnetcdf
  run:
    - curl
    - libcurl
    - hdf5
    - libnetcdf

test:
  commands:
    - test -f $PREFIX/bin/nccmp  # [unix]
    - nccmp --usage

about:
  home: https://gitlab.com/remikz/nccmp
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Comparison of NetCDF files

  description: |
    nccmp compares two NetCDF files bitwise, semantically or with a
    user defined tolerance (absolute or relative percentage). Parallel
    comparisons are done in local memory without requiring temporary
    files. Highly recommended for regression testing scientific models
    or datasets in a test-driven development environment.
  doc_url: https://gitlab.com/remikz/nccmp/-/blob/master/README.md
  dev_url: https://gitlab.com/remikz/nccmp

extra:
  recipe-maintainers:
    - zklaus
